export const RESETGAME = "RESETGAME";

export const SETPOK = "SETPOK";
export const SETGAMESTARTED = "SETGAMESTARTED";
export const SETCODEX = "SETCODEX";
export const REMOVECODEX = "REMOVECODEX";

export const SETFACTION = "SETFACTION";
export const SETUNITAVAILABLE = "SETUNITAVAILABLE";
export const APPENDUNITABILITY = "APPENDUNITABILITY";
export const REMOVEEXTRAABILITY = "REMOVEEXTRAABILITY";
export const SETUNITPROPERTIES = "SETUNITPROPERTIES";
export const SETEXTRAVICTORYPOINTS = "SETEXTRAVICTORYPOINTS";
export const SETSTARTINGFACTION = "SETSTARTINGFACTION";

export const SETTECH = "SETTECH";
export const ADDTECH = "ADDTECH";
export const REMOVETECH = "REMOVETECH";

export const ADDPLANET = "ADDPLANET";
export const EXHAUSTPLANET = "EXHAUSTPLANET";
export const REMOVEPLANET = "REMOVEPLANET";
export const EXHAUSTLEGENDARY = "EXHAUSTLEGENDARY";
export const SETPLANET = "SETPLANET";

export const ADDOBJECTIVE = "ADDOBJECTIVE";
export const COMPLETEOBJECTIVE = "COMPLETEOBJECTIVE";
export const REMOVEOBJECTIVE = "REMOVEOBJECTIVE";

export const ADDACTIONCARD = "ADDACTIONCARD";
export const REMOVEACTIONCARD = "REMOVEACTIONCARD";

export const ADDAGENDA = "ADDAGENDA";
export const REMOVEAGENDA = "REMOVEAGENDA";
export const ELECTOUTCOME = "ELECTOUTCOME";

export const SETPHASETAB = "SETPHASETAB";
export const SETCOMBATTAB = "SETCOMBATTAB";

export const ADDPROMISSORY = "ADDPROMISSORY";
export const SETPROMISSORYCOLOUR = "SETPROMISSORYCOLOUR";
export const REMOVEPROMISSORY = "REMOVEPROMISSORY";
export const SETPROMISSORYATTACHED = "SETPROMISSORYATTACHED";

export const ADDEXPLORATIONCARD = "ADDEXPLORATIONCARD";
export const REMOVEEXPLORATIONCARD = "REMOVEEXPLORATIONCARD";
export const SETATTACHEDPLANETEXPLORATION = "SETATTACHEDPLANETEXPLORATION";
export const SETATTACHEDPLANETRELIC = "SETATTACHEDPLANETERELIC";

export const ADDRELIC = "ADDRELIC";
export const REMOVERELIC = "REMOVERELIC";
export const EXHAUSTRELIC = "EXHAUSTRELIC";

export const SETLOOKUPFACTION = "SETLOOKUPFACTION";
export const ADDLOOKUPFACTION = "ADDLOOKUPFACTION";
export const REMOVELOOKUPFACTION = "REMOVELOOKUPFACTION";
