export const RESETGAME = "RESETGAME";

export const SETPOK = "SETPOK";
export const SETGAMESTARTED = "SETGAMESTARTED";

export const SETFACTION = "SETFACTION";
export const SETUNITAVAILABLE = "SETUNITAVAILABLE";

export const SETTECH = "SETTECH";
export const ADDTECH = "ADDTECH";
export const REMOVETECH = "REMOVETECH";

export const ADDPLANET = "ADDPLANET";
export const EXHAUSTPLANET = "EXHAUSTPLANET";
export const REMOVEPLANET = "REMOVEPLANET";
export const EXHAUSTLEGENDARY = "EXHAUSTLEGENDARY";
export const SETPLANET = "SETPLANET";

export const ADDOBJECTIVE = "ADDOBJECTIVE";
export const COMPLETEOBJECTIVE = "COMPLETEOBJECTIVE";
export const REMOVEOBJECTIVE = "REMOVEOBJECTIVE";

export const ADDACTIONCARD = "ADDACTIONCARD";
export const REMOVEACTIONCARD = "REMOVEACTIONCARD";

export const ADDAGENDA = "ADDAGENDA";
export const REMOVEAGENDA = "REMOVEAGENDA";
export const ELECTOUTCOME = "ELECTOUTCOME";

export const SETPHASETAB = "SETPHASETAB";
export const SETCOMBATTAB = "SETCOMBATTAB";

export const ADDPROMISSORY = "ADDPROMISSORY";
export const SETPROMISSORYCOLOUR = "SETPROMISSORYCOLOUR";
export const REMOVEPROMISSORY = "REMOVEPROMISSORY";

export const ADDEXPLORATIONCARD = "ADDEXPLORATIONCARD";
export const REMOVEEXPLORATIONCARD = "REMOVEEXPLORATIONCARD";
export const SETATTACHEDPLANET = "SETATTACHEDPLANET";
