name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  OWNER: ${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set lowercase owner
        run: echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ghcr.io/${{ env.OWNER_LC }}/ti-helper:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            docker pull ghcr.io/${{ env.OWNER_LC }}/ti-helper:latest
            docker stop ti-helper || true
            docker rm ti-helper || true
            docker run -d --name ti-helper -p 13380:80 ghcr.io/${{ env.OWNER_LC }}/ti-helper:latest